version: '3'
services:
  docker-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-node
    container_name: docker-node
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - docker-node-network
networks:
  docker-node-network: